/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AddModelRouteImport } from './routes/add-model'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as ClusterRouteImport } from './routes/cluster'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiConnectionRouteImport } from './routes/api.connection'
import { Route as ModelsModelIdRouteImport } from './routes/models_.$modelId'
import { Route as ApiOmlxSplatRouteImport } from './routes/api.omlx.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AddModelRoute = AddModelRouteImport.update({
  id: '/add-model',
  path: '/add-model',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterRoute = ClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionRoute = ApiConnectionRouteImport.update({
  id: '/api/connection',
  path: '/api/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models_/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOmlxSplatRoute = ApiOmlxSplatRouteImport.update({
  id: '/api/omlx/$',
  path: '/api/omlx/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add-model': typeof AddModelRoute
  '/cache': typeof CacheRoute
  '/cluster': typeof ClusterRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/settings': typeof SettingsRoute
  '/api/connection': typeof ApiConnectionRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/api/omlx/$': typeof ApiOmlxSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add-model': typeof AddModelRoute
  '/cache': typeof CacheRoute
  '/cluster': typeof ClusterRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/settings': typeof SettingsRoute
  '/api/connection': typeof ApiConnectionRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/api/omlx/$': typeof ApiOmlxSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add-model': typeof AddModelRoute
  '/cache': typeof CacheRoute
  '/cluster': typeof ClusterRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/monitoring': typeof MonitoringRoute
  '/settings': typeof SettingsRoute
  '/api/connection': typeof ApiConnectionRoute
  '/models_/$modelId': typeof ModelsModelIdRoute
  '/api/omlx/$': typeof ApiOmlxSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/add-model'
    | '/cache'
    | '/cluster'
    | '/diagnostics'
    | '/logs'
    | '/models'
    | '/monitoring'
    | '/settings'
    | '/api/connection'
    | '/models/$modelId'
    | '/api/omlx/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/add-model'
    | '/cache'
    | '/cluster'
    | '/diagnostics'
    | '/logs'
    | '/models'
    | '/monitoring'
    | '/settings'
    | '/api/connection'
    | '/models/$modelId'
    | '/api/omlx/$'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/add-model'
    | '/cache'
    | '/cluster'
    | '/diagnostics'
    | '/logs'
    | '/models'
    | '/monitoring'
    | '/settings'
    | '/api/connection'
    | '/models_/$modelId'
    | '/api/omlx/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AddModelRoute: typeof AddModelRoute
  CacheRoute: typeof CacheRoute
  ClusterRoute: typeof ClusterRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  MonitoringRoute: typeof MonitoringRoute
  SettingsRoute: typeof SettingsRoute
  ApiConnectionRoute: typeof ApiConnectionRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  ApiOmlxSplatRoute: typeof ApiOmlxSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-model': {
      id: '/add-model'
      path: '/add-model'
      fullPath: '/add-model'
      preLoaderRoute: typeof AddModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster': {
      id: '/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof ClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connection': {
      id: '/api/connection'
      path: '/api/connection'
      fullPath: '/api/connection'
      preLoaderRoute: typeof ApiConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models_/$modelId': {
      id: '/models_/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/omlx/$': {
      id: '/api/omlx/$'
      path: '/api/omlx/$'
      fullPath: '/api/omlx/$'
      preLoaderRoute: typeof ApiOmlxSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AddModelRoute: AddModelRoute,
  CacheRoute: CacheRoute,
  ClusterRoute: ClusterRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  MonitoringRoute: MonitoringRoute,
  SettingsRoute: SettingsRoute,
  ApiConnectionRoute: ApiConnectionRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  ApiOmlxSplatRoute: ApiOmlxSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
